/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DHLmoto.GUI;

import DHLmoto.BUS.HoaDonBUS;
import DHLmoto.BUS.KhoBUS;
import DHLmoto.BUS.PhieuNhapBUS;
import DHLmoto.BUS.SanPhamBUS;

import DHLmoto.DTO.HoaDonDTO;
import DHLmoto.DTO.KhoDTO;
import DHLmoto.DTO.PhieuNhapDTO;
import DHLmoto.DTO.SanPhamDTO;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author MINH HIEU
 */
public class NewJFrame extends javax.swing.JFrame {
    KhoBUS khobus = new KhoBUS();
    PhieuNhapBUS pnbus = new PhieuNhapBUS();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
                this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TÊN SẢN PHẨM", "NĂM RA MẮT", "GIÁ NHẬP", "SỐ LƯỢNG", "THÀNH TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("XÁC NHẬN NHẬP HÀNG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("HUỶ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Phiếu Nhập Sản Phẩm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        KhoDTO kho = new KhoDTO();
        KhoBUS n = new KhoBUS();
        PhieuNhapDTO pndto = new PhieuNhapDTO();
        String mapn = pnbus.taoPN();
        SanPhamBUS nn = new SanPhamBUS();
        PhieuNhapDTO np = new PhieuNhapDTO();
        np.setMaPhieuNhap(pnbus.taoPN());
        SanPhamDTO sp = new SanPhamDTO();
        for(int i = 0 ; i<jTable1.getRowCount();i++){
            if(nn.ktName((String)jTable1.getModel().getValueAt(i, 0),(int)jTable1.getModel().getValueAt(i, 1)) == true ){
                                                int kt2 = khobus.LaySL(nn.layMA((String)jTable1.getModel().getValueAt(i, 0)))+(int)jTable1.getModel().getValueAt(i, 3);
                                                np.setMaSanPham(nn.layMA((String)jTable1.getModel().getValueAt(i, 0)));
                                                np.setNgayNhap(String.valueOf(java.time.LocalDate.now()));
                                                np.setTenSanPham((String)jTable1.getModel().getValueAt(i, 0));
                                                np.setGiaNhap((long)jTable1.getModel().getValueAt(i, 2));
                                                np.setSoLuong((int)jTable1.getModel().getValueAt(i, 3));
                                                np.setNamRaMat((int)jTable1.getModel().getValueAt(i, 1));
                                                np.setTongTien((long)jTable1.getModel().getValueAt(i, 4));
                                                pnbus.addPN(np);
                                                n.UpdateSL(nn.layMA((String)jTable1.getModel().getValueAt(i, 0)),kt2  );}
            else {
                sp.setMaSanPham(nn.taosp());
                sp.setTenSanPham((String)jTable1.getModel().getValueAt(i, 0));
                sp.setGiaBanRa((long)jTable1.getModel().getValueAt(i, 2));
                sp.setNamRaMat((int)jTable1.getModel().getValueAt(i, 1));
                sp.setTT(1);
                nn.addSP(sp);
                kho.setTt(1);
                kho.setMaSanPham(sp.getMaSanPham());
                kho.setSoLuong((int)jTable1.getModel().getValueAt(i, 3));
                khobus.addkho(kho);
                                                np.setMaSanPham(nn.layMA((String)jTable1.getModel().getValueAt(i, 0)));
                                                np.setNgayNhap(String.valueOf(java.time.LocalDate.now()));
                                                np.setTenSanPham((String)jTable1.getModel().getValueAt(i, 0));
                                                np.setGiaNhap((long)jTable1.getModel().getValueAt(i, 2));
                                                np.setSoLuong((int)jTable1.getModel().getValueAt(i, 3));
                                                np.setNamRaMat((int)jTable1.getModel().getValueAt(i, 1));
                                                np.setTongTien((long)jTable1.getModel().getValueAt(i, 4));
                                                pnbus.addPN(np);
            }}
                mainFrame mf= new mainFrame();
                mf.selectql();
                mf.showhoadonql();
                mf.setVisible(true);
                dispose(); 
                JOptionPane.showMessageDialog(rootPane,"NHẬP HÀNG THÀNH CÔNG");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mainFrame mf= new mainFrame();
                mf.selectql();
                mf.showhoadonql();
                mf.setVisible(true);
                dispose(); 
                JOptionPane.showMessageDialog(rootPane,"ĐÃ HUỶ NHẬP HÀNG");
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public static void Chay(XSSFSheet sheet){
        Row row;
        String TenSanPham = null;
        int NamRaMat = 0;
        long Gia = 0;
        int SoLuong = 0;
        long thanhtien = 0;
        HoaDonDTO ds = new HoaDonDTO();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("TÊN SẢN PHẨM");
        model.addColumn("NĂM RA MẮT");
        model.addColumn("GIÁ NHẬP");
        model.addColumn("SỐ LƯỢNG");
        model.addColumn("THÀNH TIỀN");
        jTable1.setModel(model);
        model.setRowCount(0);
        ArrayList<PhieuNhapDTO> hoadondto = new ArrayList<PhieuNhapDTO>();
        PhieuNhapBUS aa = new PhieuNhapBUS();
        hoadondto = aa.showpn();
        for (int i = 1; i <= sheet.getLastRowNum(); i++)
        {
            row = sheet.getRow(i);
            TenSanPham = (String)row.getCell(0).getStringCellValue().trim();
            NamRaMat = (int)row.getCell(1).getNumericCellValue();
            Gia = (long)row.getCell(2).getNumericCellValue();
            SoLuong = (int)row.getCell(3).getNumericCellValue();
            thanhtien = (long)row.getCell(4).getNumericCellValue();
            Object[] a = {TenSanPham, NamRaMat,Gia,SoLuong,thanhtien};
            model.addRow(a);
        }
    }
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
